package com.comp2042.event;

import com.comp2042.data.DownData;
import com.comp2042.data.ViewData;

/**
 * The {@code InputEventListener} interface defines callbacks for movement and drop events generated by user input
 * or the game loop. Implementations update the board and return view data or movement results for rendering.
 *
 * <p>See the source code at
 * <a href="https://github.com/JIMMY081105/CW2025/tree/master/src/main/java/com/comp2042/event/InputEventListener.java">
 * InputEventListener.java</a>
 */
public interface InputEventListener {

    /**
     * Handles a downward move, potentially locking and clearing rows.
     *
     * @param event move metadata.
     * @return result containing clear information and view data.
     */
    DownData onDownEvent(MoveEvent event);

    /**
     * Handles a left move request.
     *
     * @param event move metadata.
     * @return updated view data.
     */
    ViewData onLeftEvent(MoveEvent event);

    /**
     * Handles a right move request.
     *
     * @param event move metadata.
     * @return updated view data.
     */
    ViewData onRightEvent(MoveEvent event);

    /**
     * Handles a rotation request.
     *
     * @param event move metadata.
     * @return updated view data after rotation attempt.
     */
    ViewData onRotateEvent(MoveEvent event);

    /**
     * Handles a hard drop request.
     *
     * @param event move metadata.
     * @return result containing clear information and view data.
     */
    DownData onHardDropEvent(MoveEvent event);
}
